name: Prevent Direct PRs to Main

on:
  pull_request:
    branches:
      - main

jobs:
  block-direct-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from `development`
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" != "development" ]]; then
            echo "Pull Requests to main must come from development!";
            exit 1;
          fi
